import "./timeline.css"

const Timeline = () => (
	<div class="timeline">
		<TimelineBox c="left" title="Blue Demon" date="January 2019" link="https://github.com/jchernin4/BlueDemon" description='My first time using Git and Github. A friend and I worked on an algorithm for a turn-based strategy game called "Fruit Bots", where it competed against other algorithms to collect fruits.'/>
		<TimelineBox c="right" title="Poseidon" date="January 2019" link="https://github.com/jchernin4/Poseidon" description="A tool for Discord to automate tasks for administrators, along with some miscellaneous commands. Used by over 100,000 people at it's peak."/>
		<TimelineBox c="left" title="Binance Trader" date="October 2019" link="https://github.com/jchernin4/BinanceTrader" description="A simple algorithm for automatically trading crypto on the Binance exchange using their API. Based on the MACD, Stochastic, and RSI indicators."/>
		<TimelineBox c="right" title="Unnamed Singleplayer Game" date="February 2020" link="https://github.com/jchernin4/Singleplayer" description="A simple singleplayer FPS template I made to practice using Unity."/>
		<TimelineBox c="left" title="Tarkov Market Bot" date="March 2020" link="https://github.com/jchernin4/Tarkov-Market-Bot" description="A market arbitrage tool I made for the game Escape from Tarkov. It would scrape price data from the user's screen, and automatically buy items below a certain price."/>
		<TimelineBox c="right" title="Rust Wallpaper Changer" date="July 2020" link="https://github.com/jchernin4/Rust-Wallpaper" description="Automatically updated my computer's wallpaper based on the time of day to match the time of day in the image."/>
		<TimelineBox c="left" title="Serum" date="July 2020" link="N/A" description="A remote administration tool written in C# that allowed administrators to access files, processes, and more by remotely connecting to a computer over TCP."/>
		<TimelineBox c="right" title="Barter Signs" date="December 2020" link="https://github.com/jchernin4/BarterSigns" description="A Minecraft plugin that allowed users to trade in-game currency for items by clicking on a sign."/>
		<TimelineBox c="left" title="MCAntiCheat" date="December 2020" link="https://github.com/jchernin4/MCAntiCheat" description="Another Minecraft plugin to detect players using certain cheats by keeping track of how quickly they completed certain tasks, like collecting different kinds of rare materials."/>
		<TimelineBox c="right" title="AimTraining" date="January 2021" link="https://github.com/jchernin4/AimTraining" description="A set of plugins I used for an aim training server on the game Rust."/>
		<TimelineBox c="left" title="Guitar Keyboard Controller" date="February 2021" link="https://github.com/jchernin4/Guitar-Keyboard-Controller" description="A program I made for a friend that allows a user to play notes on a guitar into their computer's microphone, which would be translated into keyboard clicks. This way, the user could play a video game using a guitar."/>
		<TimelineBox c="right" title="Franklin" date="April 2021" link="https://github.com/jchernin4/Franklin" description="Another Discord bot I made for my friend that had a basic currency and xp system, allowing players to compete to be the wealthiest user."/>
		<TimelineBox c="left" title="Econ" date="April 2021" link="https://github.com/jchernin4/Econ" description='Another Discord economy bot, but this one was a lot more advanced. It allowed users to "invest" their currency into stocks, which followed real life stock market prices through an algorithm that combined different assets into a made-up one that players could purchase. It also allowed players to gamble their money with games like "roulette" and "coinflip".'/>
		<TimelineBox c="right" title="Multiplayer Test" date="May 2021" link="https://github.com/jchernin4/Multiplayer-Test" description="Getting back into Unity development, I made a testing project using the Mirror package to create a multiplayer 3D game."/>
		<TimelineBox c="left" title="Spelling Bee" date="May 2021" link="https://github.com/jchernin4/Spelling-Bee" description="An Amazon Alexa game I made for a school project, where the player is asked to spell a word correctly to win."/>
		<TimelineBox c="right" title="Login System" date="July 2021" link="https://github.com/jchernin4/Login-System" description="A boilerplate Java login system for a website using MongoDB as a database and Javalin (a wrapper for Jetty) as a webserver."/>
		<TimelineBox c="left" title="Ameritrade Portfolio Viewer" date="August 2021" link="https://github.com/jchernin4/AmeritradePortfolioViewer" description="A tool I used to display a graph of the historical balance of a TD Ameritrade account. I made this because the regular Ameritrade app counted deposits as profit, so I automatically excluded deposits in this tool."/>
		<TimelineBox c="right" title="Grapple Shooter" date="October 2021" link="https://github.com/jchernin4/GrappleShooter" description="A simple project I made with a friend to teach him how to use the basics of Unity, as well as how to create a multiplayer game. This was a physics-based game where a player could use their grappling hook to latch onto blocks in an arena while shooting at their opponents."/>
		<TimelineBox c="left" title="Santa" date="December 2021" link="https://github.com/jchernin4/Santa" description='A Discord bot I made for my friends to automatically assign another member of the group to buy a gift for as a "secret santa."'/>
		<TimelineBox c="right" title="Project Zero" date="May 2022" link="https://github.com/jchernin4/Project-Zero" description="A game similar to the game Ravenfield. The player is in control of a large army of AI-controlled soliders, and must capture areas of interest in order to earn points. The twist was that the player could control where the AI bots move to by selecting them on a map and clicking on a point that they want to control. It was meant to be a multiplayer game, but was never finished."/>
		<TimelineBox c="left" title="Martingale" date="April 2021" link="https://github.com/jchernin4/Martingale" description="A simple demonstration of the martingale betting strategy, where after each loss, you double your initial bet."/>
		<TimelineBox c="right" title="Pathfinding Visualizer" date="May 2020" link="https://github.com/jchernin4/Pathfinding-Visualizer-V4" description="Visualizer for a pathfinding algorithm."/>
		<TimelineBox c="left" title="GreenSolve" date="November 2022" link="https://github.com/jchernin4/GreenSolve-HackPSU2022" description="A submission for HackPSU 2022, which won in two categories: Sustainability and Most Creative Use of Twilio. This application was focused on connecting people in the same area to work together on green projects such as park cleanups and community gardens by allowing organizers to send out a text message notification about an event to all users that are registered in the same zip code."/>
		<TimelineBox c="right" title="CHiP" date="November 2022" link="https://github.com/jchernin4/CHiP" description="Another Discord bot that allowed users to compete in 10 different games against other players for a fake currency, including blackjack, connect4, slots, roulette, and more. Allowed users to buy fictional items such as cars which they could upgrade and race against other players for more currency, or generators which could be upgraded and would passively provide players with more income."/>
		<TimelineBox c="left" title="Bloons TD6 Bot" date="September 2021" link="https://github.com/jchernin4/BloonsTD6Bot" description="A tool that would automatically play the game Bloons Tower Defense 6 by controlling the player's actions."/>
		<TimelineBox c="right" title="File Opener" date="January 2021" link="https://github.com/jchernin4/File-Opener" description="A joke project I made for a friend that opens every file on the user's computer."/>
		<TimelineBox c="left" title="Footbig" date="April 2020" link="https://github.com/jchernin4/Footbig" description="A horror game I made with a friend where the player must defend themselves from Bigfoot for as long as possible."/>
		<TimelineBox c="right" title="MidNight Club" date="August 2021" link="https://github.com/jchernin4/MidNightClub" description='A simple car drifting game made in Unity. Taught me how to use their new input controller to easily work on both a keyboard and an Xbox controller.'/>
		<TimelineBox c="left" title="Maze Game" date="December 2019" link="https://github.com/jchernin4/Maze-Thing" description="A console maze game where the player must move around to escape the maze."/>
		<TimelineBox c="right" title="Remote Keyboard Controller" date="November 2020" link="https://github.com/jchernin4/RemoteKeyboardController" description="A program to control another user's keyboard while they are playing a game. I made this for a friend that doesn't fully understand what I'm doing here, so it has a ton of comments explaining everything."/>
		<TimelineBox c="left" title="Rust Skin Changer Plugin" date="January 2021" link="https://github.com/jchernin4/Rust-Skin-Changer-Plugin" description="A plugin that allowed users to change how their in-game items looked in the game Rust."/>
		<TimelineBox c="right" title="Space Engineers Scripts" date="May 2021" link="https://github.com/jchernin4/Space-Engineers-Scripts" description="A collection of scripts to automate certain tasks in the game Space Engineers, which I made for a friend. It allows you to monitor how many resources you have, automatically control a mining ship, and a few other things."/>
		<TimelineBox c="left" title="SplitStats" date="August 2021" link="https://github.com/jchernin4/SplitStats" description="A Discord bot for the game Splitgate, which allowed users to check the in-game statistics for themselves or other players."/>
		<TimelineBox c="right" title="Stats" date="January 2021" link="https://github.com/jchernin4/Stats" description="A Rust plugin that allowed players to track certain statistics, such as deaths and kills."/>
		<TimelineBox c="left" title="Steam Idler" date="Febuary 2021" link="https://github.com/jchernin4/Steam-Idler" description="A tool for the game launcher Steam, which allows users to appear as though they are playing a game without actually having a game open. Useful to passively receive Steam trading cards, which can be sold for money."/>
		<TimelineBox c="right" title="RIT Brickhack" date="Febuary 2023" link="https://github.com/jchernin4/RIT-Brickhack" description="A submission for RIT's Brickhack hackathon. It is a multiplayer game made in Unity, which let players compete to solve math problems before the other player."/>
		<TimelineBox c="left" title="StudyBuddy" date="April 2023" link="https://github.com/jchernin4/StudyBuddy" description="A submission for HackPSU Spring 2023, where users could find students in their classes to study with."/>
		<TimelineBox c="right" title="Neurosis" date="January 2023" link="https://github.com/jchernin4/Neurosis" description="A horror puzzle game with a deep story about a teenager with depression who must escape a dream world that is fillied with monsters of his own creation. This game has its own page on the game launcher Steam, but was never finished."/>
		<TimelineBox c="left" title="Zenith" date="April 2023" link="https://github.com/jchernin4/Zenith" description="A recoil control script for the game Rust with many features, such as humanization, smoothness, process hiding, and security features like hardware ID detection which made sure an account that purchased access to the script would only be useable on a single computer."/>
		<TimelineBox c="right" title="The Eden Project" date="May 2023" link="https://github.com/jchernin4/TheEdenProject" description="A singleplayer tower defense game where the player is stranded on a planet and must defend themselves from alien enemies and helicopters. They do this by placing turrents to defend their space station while managing different resources like power and iron to craft and upgrade more turrets."/>
		<TimelineBox c="left" title="Adlite" date="October 2023" link="https://github.com/jchernin4/AdLite" description="A submission to HackPSU Fall 2023, which won first place in both the Entrepreneurship and Best Use of Taipy categories. It provided an alternative advertisement solution to traditional ads by instead using a cryptocurrency miner to act as a less invasive option for those that prefer to not have a cluttered webpage."/>
		<TimelineBox c="right" title="AsciiJack" date="January 2024" link="https://github.com/jchernin4/asciijack" description="A console-based blackjack game."/>
		<TimelineBox c="left" title="Forza Horizon 5 Sniper" date="November 2021" link="https://github.com/jchernin4/FH5Sniper" description="A bot that automatically purchased cars on the auction house below a specified price in the game Foriza Horizon 5."/>
		<TimelineBox c="right" title="The Consult" date="January 2024" link="https://github.com/jchernin4/TheConsult" description="A website similar to Snopes, which crowdsourced votes for news articles on whether the article was trustworthy or not, in an attempt to combat misinformation and fake news."/>
		<TimelineBox c="left" title="Task Master" date="Febuary 2024" link="https://github.com/jchernin4/task-master" description="A simple todo list app and calendar to help improve productivity."/>
	</div> 
);

const TimelineBox = ({ c, title, date, link, description }) => (
	<div className={`container ${c}`}>
		<div className="content">
			<p>
				<strong>{title}</strong><br/>
				<i>{date}</i><br/>
				<a href={link} target="_blank" rel="noreferrer">{link}</a><br/>
				{description}
			</p>
		</div>
	</div>
);

Timeline.TimelineBox = TimelineBox;

export default Timeline;
